USE signbridge;
ALTER TABLE users ADD COLUMN privacy_consent TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN training_consent TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN marketing_consent TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN consent_at TIMESTAMP NULL;
