CREATE DATABASE IF NOT EXISTS signbridge CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE signbridge;
CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 language VARCHAR(10) NOT NULL DEFAULT 'en',
 privacy_consent TINYINT(1) NOT NULL DEFAULT 0,
 training_consent TINYINT(1) NOT NULL DEFAULT 0,
 marketing_consent TINYINT(1) NOT NULL DEFAULT 0,
 consent_at TIMESTAMP NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_preferences (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 favourites JSON NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 CONSTRAINT fk_preferences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
